server:
  forward-headers-strategy: framework

jwt:
  secret: ${SECRET_KEY}

admin:
  email: "admin@example.com"
  password: "Admin@123"

tmdb:
  api:
    token: ${TMDB_TOKEN}

spring:
  application:
    name: Trailers

  brevo:
    sender-email: ${BREVO_SENDER_EMAIL}
    api-key: ${BREVO_API_KEY}
    sender-name: ${BREVO_SENDER_NAME}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
